name: time_widgets
description: A smart timetable application for students
publish_to: 'none'
version: 0.1.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  file_picker: ^8.0.3
  system_tray: ^2.0.3
  window_manager: ^0.3.7
  ntp: ^2.0.0
  dynamic_color: ^1.6.8
  url_launcher: ^6.2.5
  desktop_multi_window: ^0.3.0
  launch_at_startup: ^0.5.1
  package_info_plus: ^9.0.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  glados: ^1.1.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/